# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  java.version: '17.0.1'

jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '17.0.1'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'Installer'
          cleanDestinationDirectory: true
      - task: Gradle@1
        inputs:
          workingDirectory: ''
          gradleWrapperFile: 'gradlew'
          gradleOptions: '-Xmx3072m'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '17.0.1'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          tasks: 'build'

