trigger:
  - main

variables:
  - group: seed-server-variables

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'Your-Azure-Subscription'
    KeyVaultName: 'your-keyvault-name'
    SecretsFilter: 'DB_USERNAME,DB_PASSWORD'
    RunAsPreJob: true

- script: |
    chmod +x ./gradlew
    ./gradlew build
  displayName: 'Build with Gradle Wrapper'
  env:
    DB_USERNAME: $(DB_USERNAME)
    DB_PASSWORD: $(DB_PASSWORD)

- task: Docker@2
  inputs:
    containerRegistry: 'your-acr-connection'
    repository: 'seed-server'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: |
      $(Build.BuildId)
      latest
