app:
  environment: dev

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/sample?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: ${DB_USERNAME:user}
    password: ${DB_PASSWORD:password}
  kafka:
    bootstrap-servers: b-1.cpskafkastg.n37ial.c2.kafka.cn-north-1.amazonaws.com.cn:9096,b-2.cpskafkastg.n37ial.c2.kafka.cn-north-1.amazonaws.com.cn:9096
