app:
  environment: dev

server:
  port: 6666
spring:

  datasource:
    url: jdbc:mysql://120.48.21.80:3306/sample?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    # Hikari pool https://github.com/brettwooldridge/HikariCP
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 连接池中允许的最小连接数。缺省值：10
      minimum-idle: 10
      # 连接池中允许的最大连接数。缺省值：10
      maximum-pool-size: 100
      # 自动提交
      auto-commit: true
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 30000
      # 连接池名字
      pool-name: MyHikariCP
      # 一个连接的生命时长（毫秒，值0表示无限生命周期，默认1800000即30分钟），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      max-lifetime: 1800000
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      # 数据库连接测试语句
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        # 解决驼峰型字段建表时自动转化为下划线的问题
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    # 日期序列化格式
    date-format: yyyy-MM-dd HH:mm:ss
  kafka:
    # 集群地址， 任意配一台可用地址即可
    bootstrap-servers: 10.209.21.37:9092，10.209.21.37:9093, 10.209.21.37:9094
    # 生产者配置
    producer:
      # 重试次数
      retries: 3
      # 一次最多发送数据量
      batch-size: 16384
      # 32M批处理缓冲区
      buffer-memory: 33554432
      # 序列化
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 消息确认
      acks: "1"
      # 发送延迟
      properties:
        request:
          timeout:
            ms: 60000
        linger:
          ms: 1000
    consumer: # 消费者配置
      group-id: 0 # group-id
      enable-auto-commit: false # 是否开启自动提交
      auto-commit-interval: 100 # consumer自动向zookeeper提交offset的频率
      properties: # 消费超时时间，大小不能超过session.timeout.ms，默认：3000
        session:
          timeout:
            ms: 15000
        request:
          timeout:
            ms: 60000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # 反序列化
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      fetch-max-wait: 600000 # 配置consumer最多等待response多久
      max-poll-records: 50 # max.poll.records条数据需要在session.timeout.ms这个时间内处理完
#logging:
#  level:
#    org:
#      apache:
#        kafka: DEBUG