app:
  environment: dev

server:
  port: 6666

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import:
      - kafka.yml

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/sample?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 10
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    table: flyway_schema_history
    validate-on-migrate: true

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
#logging:
#  level:
#    org:
#      apache:
#        kafka: DEBUG

jwt:
  secret: ${JWT_SECRET:your-secret-key}
  expiration: 86400000  # 24小时
