app:
  environment: dev

server:
  port: 6666
spring:

  datasource:
    url: jdbc:mysql://120.48.21.80:3306/sample?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 123456
    # Hikari pool https://github.com/brettwooldridge/HikariCP
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      # 连接池中允许的最小连接数。缺省值：10
      minimum-idle: 10
      # 连接池中允许的最大连接数。缺省值：10
      maximum-pool-size: 100
      # 自动提交
      auto-commit: true
      # 一个连接idle状态的最大时长（毫秒），超时则被释放（retired），缺省:10分钟
      idle-timeout: 30000
      # 连接池名字
      pool-name: MyHikariCP
      # 一个连接的生命时长（毫秒，值0表示无限生命周期，默认1800000即30分钟），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒
      max-lifetime: 1800000
      # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 缺省:30秒
      connection-timeout: 30000
      # 数据库连接测试语句
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        # 解决驼峰型字段建表时自动转化为下划线的问题
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    # 日期序列化格式
    date-format: yyyy-MM-dd HH:mm:ss
#logging:
#  level:
#    org:
#      apache:
#        kafka: DEBUG