app:
  environment: prod

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/sample?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  kafka:
    bootstrap-servers: b-1.cpskafkastg.n37ial.c2.kafka.cn-north-1.amazonaws.com.cn:9096,b-2.cpskafkastg.n37ial.c2.kafka.cn-north-1.amazonaws.com.cn:9096
